### PR TITLE
Add support for OpenLayers 3

### LINKED ISSUE #17: Openlayers integration
Hi there,

would it be difficult to integrate openlayers to famous-map? I need this, because the others don't provide the functionality of rotating the map.

Or is it possible to rotate the maps provided by the famous-map package?

Regards

### PR DESCRIPTION
**Pull request by ahocevar**
This implements all functions in MapView.js for OpenLayers 3. The demo example now also has an OpenLayers 3 version. Rotation support is implemented as well.

Fixes #17.

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Awesome Andreas, thanks very much for that. I will review and pull soon. Awesome, thanks!

**Comment by der-ede** [comment]
Hi @IjzerenHein,

has this pull request been added so far?

Regards

**Comment by IjzerenHein** [comment]
Hi, no I'm sorry not yet, I've been too busy. I will try to schedule some time for this, either this or next week.

**Comment by IjzerenHein** [comment]
Hi, I've merged your code, it works beautifully, thanks very much for this contribution!

**Comment by der-ede** [comment]
Hi @IjzerenHein and @ahocevar,

thank you again, works like a breeze :)
Rotation also goes.
Next I have to try it with Meteor famono.

**Comment by ahocevar** [comment]
Thanks for merging!

**Pull request merged**
